image: docker:latest

services:
  - docker:dind

before_script:
  - docker info

variables:
  DOCKER_HOST: tcp://localhost:2375  

build:
  stage: build
  script:
  - docker run --rm=true -v $PWD:/go/src/krak8s golang:1.8 bash -c "cd /go/src/krak8s; make containerprep"
  - docker login -u ${REGISTRY_USERNAME} -p ${REGISTRY_PASSWORD} ${REGISTRY_HOST}
  - docker build -t ${REGISTRY_HOST}/${REGISTRY_IMAGE_NAME}:${CI_COMMIT_SHA} .
  - docker push ${REGISTRY_HOST}/${REGISTRY_IMAGE_NAME}:${CI_COMMIT_SHA}


