basePath: /v1
consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
host: localhost:8080
info:
  description: API Service for Kraken and Kubernetes Commands
  title: krak8s API Server
  version: ""
paths:
  /mongo/:
    post:
      description: deploy MongoDB for client to namespace
      operationId: mongodb#deploy
      parameters:
      - description: client identifier
        in: query
        name: client
        required: false
        type: string
      - description: namesace identifier
        in: query
        name: ns
        required: false
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: OK
      schemes:
      - http
      summary: deploy mongodb
      tags:
      - mongodb
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
schemes:
- http
swagger: "2.0"
